# Generated by Django 3.1.4 on 2020-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordx', models.CharField(max_length=10, verbose_name='coordenada X')),
                ('coordy', models.CharField(max_length=10, verbose_name='coordenada Y')),
                ('valormax', models.CharField(max_length=35, verbose_name='valor maximo')),
                ('valormin', models.CharField(max_length=35, verbose_name='valor minimo')),
                ('valorprom', models.CharField(max_length=35, verbose_name='valor promedio')),
                ('frecuencia', models.CharField(max_length=35, verbose_name='frecuencia de Valor maximo')),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
            },
        ),
    ]
