# Generated by Django 3.1.4 on 2020-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frec_max', models.CharField(max_length=12, verbose_name='frecuencia maxima')),
                ('frec_min', models.CharField(max_length=15, verbose_name='frecuencia minuma')),
                ('maker', models.CharField(max_length=15, verbose_name='fabricante')),
            ],
            options={
                'verbose_name': 'Especificacion',
                'verbose_name_plural': 'Especificaciones',
            },
        ),
    ]
