# Generated by Django 3.1.4 on 2020-12-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipament', '0002_specific'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specific',
            old_name='frec_min',
            new_name='frecmin',
        ),
        migrations.RemoveField(
            model_name='specific',
            name='frec_max',
        ),
        migrations.AddField(
            model_name='specific',
            name='frecmax',
            field=models.CharField(default=1, max_length=15, verbose_name='frecuencia maxima'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specific',
            name='maker',
            field=models.CharField(max_length=35, verbose_name='fabricante'),
        ),
    ]
