# Generated by Django 3.1.4 on 2020-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipament', '0005_auto_20201204_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paremetrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweeptime', models.CharField(max_length=15, verbose_name='tiempo de barrido')),
                ('resolution', models.CharField(max_length=35, verbose_name='freciencia de resolucion')),
                ('sample', models.CharField(max_length=20, verbose_name='muesta')),
                ('central', models.CharField(max_length=20, verbose_name='frecuencia central')),
                ('band', models.CharField(max_length=20, verbose_name='ancho de banda')),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='nombre')),
                ('points', models.CharField(max_length=10, verbose_name='numero de puntos')),
                ('date', models.CharField(max_length=13, verbose_name='fecha')),
                ('duration', models.CharField(max_length=15, verbose_name='duracion')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
    ]
