# Generated by Django 3.1.4 on 2020-12-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipament', '0006_paremetrs_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=30, unique=True, verbose_name='poliza')),
                ('purchase', models.CharField(max_length=25, verbose_name='compra')),
                ('datepurch', models.CharField(max_length=25, verbose_name='fecha de compra')),
                ('datemake', models.CharField(max_length=25, verbose_name='fecha de fabricacion')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
