# Generated by Django 3.1.4 on 2020-12-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipament', '0007_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='Routes',
        ),
    ]
